version: "2"

services:
  pg:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur:0.1.0-stable
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    depends_on:
      - pg

  conjur-service-broker:
    image: conjur-service-broker
    build: ./
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_APPLIANCE_URL: http://conjur
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY:
    command: rails s -p 3000 -b 0.0.0.0
    expose:
      - "3000"
    volumes:
      - "./:/app"

  tests:
    image: conjur-service-broker
    build: ./
    volumes:
      - "./:/app"
