FROM ruby:3.1
MAINTAINER CyberArk Software Ltd.

# This is a Dockerfile for the Service Broker image that is used in
# development. This differs from the production image in that:
#   - Repository tree will be volume mounted rather than copied
#   - Gem dependencies from the 'development' group are included

RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y build-essential \
                       libpq-dev \
                       zip

COPY Gemfile \
     Gemfile.lock /tmp/
WORKDIR /tmp

RUN bundle config set --local frozen 'true' && \
    bundle config set --local system 'true' && \
    bundle config set --local with 'development' && \
    bundle config set --local deployment 'false' && \
    bundle install

RUN mkdir -p /app
WORKDIR /app
