FROM conjur-service-broker

RUN apt-get install -y apt-transport-https \
                       ca-certificates \
                       openssl

# Install the Cloud Foundry CLI
RUN wget -q https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key && \
    apt-key add cli.cloudfoundry.org.key && \
    echo "deb https://packages.cloudfoundry.org/debian stable main" > /etc/apt/sources.list.d/cloudfoundry-cli.list && \
    apt-get update && \
    apt-get install -y cf-cli
