version: "2"

services:
  pg:
    image: postgres:9.3

  conjur_5:
    image: cyberark/conjur:0.3.0-stable
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    ports:
      - 80:80
    depends_on:
      - pg

  conjur_4:
    image: registry2.itci.conjur.net/conjur-appliance-cuke-master:4.9-stable
    security_opt:
      - seccomp:unconfined
    environment:
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY: secret
    volumes:
      - ./ci/policy.yml:/etc/policy.yml:ro
    ports:
      - 8443:443

  client:
    image: conjurinc/cli5
    depends_on: [ conjur_5 ]
    environment:
      CONJUR_APPLIANCE_URL: http://conjur_5
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_API_KEY:
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - "./:/app"

  conjur-service-broker:
    image: conjur-service-broker
    build: ./
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_APPLIANCE_URL:
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY:
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - "./:/app"

  service-broker-bad-url:
    image: conjur-service-broker
    build: ./
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_APPLIANCE_URL: http://badurl.invalid
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY: doesntmatter
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3001 -b 0.0.0.0 -P tmp/pids/server1.pid
    expose:
      - "3001"
    volumes:
      - "./:/app"

  service-broker-bad-key:
    image: conjur-service-broker
    build: ./
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_APPLIANCE_URL:
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY: 123badconjurkey
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3002 -b 0.0.0.0 -P tmp/pids/server2.pid
    expose:
      - "3002"
    volumes:
      - "./:/app"

  service-broker-alt-policy:
    image: conjur-service-broker
    build: ./
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: host/cf-service-broker
      CONJUR_APPLIANCE_URL:
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY:
      CONJUR_POLICY:
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3003 -b 0.0.0.0 -P tmp/pids/server3.pid
    expose:
      - "3003"
    volumes:
      - "./:/app"

  tests:
    image: conjur-service-broker
    build: ./
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_APPLIANCE_URL:
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY:
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    volumes:
      - "./:/app"
