version: "2"

services:
  pg:
    image: postgres:9.3

  conjur_5:
    image: cyberark/conjur:latest
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    ports:
      - 80:80
    depends_on:
      - pg

  conjur_4:
    image: registry2.itci.conjur.net/conjur-appliance-cuke-master:4.9-stable
    security_opt:
      - seccomp:unconfined
    environment:
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY: secret
    volumes:
      - ./policy/policy_v4.yml:/etc/policy.yml:ro
    ports:
      - 8443:443

  client:
    image: cyberark/conjur-cli:5
    depends_on: [ conjur_5 ]
    environment:
      CONJUR_APPLIANCE_URL: http://conjur_5
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_API_KEY:
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - "./:/app"

  conjur-service-broker:
    image: conjur-service-broker
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: host/cf-service-broker
      CONJUR_POLICY: cf
      CONJUR_APPLIANCE_URL:
      CONJUR_FOLLOWER_URL: ""
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY:
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3000 -b 0.0.0.0
    ports:
      - 3000:3000

  service-broker-bad-url:
    image: conjur-service-broker
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_APPLIANCE_URL: http://badurl.invalid
      CONJUR_FOLLOWER_URL: ""
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY: doesntmatter
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3001 -b 0.0.0.0 -P tmp/pids/server1.pid
    expose:
      - "3001"

  service-broker-bad-key:
    image: conjur-service-broker
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_APPLIANCE_URL:
      CONJUR_FOLLOWER_URL: ""
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY: 123badconjurkey
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3002 -b 0.0.0.0 -P tmp/pids/server2.pid
    expose:
      - "3002"

  service-broker-alt-policy:
    image: conjur-service-broker
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: host/cf-service-broker
      CONJUR_APPLIANCE_URL:
      CONJUR_FOLLOWER_URL: ""
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY:
      CONJUR_POLICY:
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3003 -b 0.0.0.0 -P tmp/pids/server3.pid
    expose:
      - "3003"

  service-broker-bad-host:
    image: conjur-service-broker
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: host/bad-service-broker
      CONJUR_APPLIANCE_URL:
      CONJUR_FOLLOWER_URL: ""
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY:
      CONJUR_POLICY:
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3004 -b 0.0.0.0 -P tmp/pids/server4.pid
    expose:
      - "3004"

  service-broker-follower-url:
    image: conjur-service-broker
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_APPLIANCE_URL:
      CONJUR_FOLLOWER_URL:
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY:
      CONJUR_POLICY:
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
    command: rails s -p 3005 -b 0.0.0.0 -P tmp/pids/server5.pid
    expose:
      - "3005"

  tests:
    image: conjur-service-broker-test
    build:
      context: ./
      dockerfile: Dockerfile.test
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_APPLIANCE_URL:
      CONJUR_FOLLOWER_URL:
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY:
      CONJUR_SSL_CERTIFICATE:
      CONJUR_VERSION:
      CF_API_ENDPOINT:
      PCF_CONJUR_APPLIANCE_URL:
      CF_CI_USER:
      CF_CI_PASSWORD:
      CF_ADMIN_PASSWORD:
      PCF_CONJUR_ACCOUNT:
      PCF_CONJUR_USERNAME:
      PCF_CONJUR_API_KEY:
      PCF_CONJUR_SSL_CERT:
    volumes:
      - "./:/app"
