FROM conjur-service-broker

# Install all the dependencies (including test/dev ones)
RUN bundle install --with development test

RUN apt-get install -y apt-transport-https ca-certificates openssl

# Install the Cloud Foundry CLI
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add - && \
    echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list && \
    apt-get update -y && \
    apt-get install -y cf-cli
