FROM ruby:2.7
MAINTAINER CyberArk Software Ltd.

# This is a Dockerfile for a Service Broker test client image. The repository
# tree will be volume mounted to test client containers so that any source
# code changes will be visible from within the container.

RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y apt-transport-https \
                       ca-certificates \
                       build-essential \
                       libpq-dev \
                       openssl \
                       vim \
                       zip

# Install the Cloud Foundry CLI
RUN wget -q https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key && \
    apt-key add cli.cloudfoundry.org.key && \
    echo "deb https://packages.cloudfoundry.org/debian stable main" > /etc/apt/sources.list.d/cloudfoundry-cli.list && \
    apt-get update && \
    apt-get install -y cf-cli

# Install all the ruby dependencies (including test ones)
COPY Gemfile \
     Gemfile.lock /tmp/
WORKDIR /tmp

# For bundle version < 2.0, bundle remembers the groups that had been
# excluded for the previous invocation of bundle. So use `--with`
# to explicitly include the test group.
RUN bundle install --no-deployment --frozen --system --with test --without development

RUN mkdir -p /app
WORKDIR /app
