version: "2"

x-conjur-credentials: &conjur-credentials
  CONJUR_ACCOUNT: cucumber
  CONJUR_AUTHN_LOGIN: admin
  CONJUR_APPLIANCE_URL: http://conjur
  CONJUR_AUTHN_API_KEY:

services:
  pg:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur:0.3.0-stable
    command: server -a cucumber
    environment:
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_DATA_KEY: 'WMfApcDBtocRWV+ZSUP3Tjr5XNU+Z2FdBb6BEezejIs='
    depends_on:
      - pg

  conjur-service-broker:
    image: conjur-service-broker
    build: ./
    environment:
      << : *conjur-credentials
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
    command: rails s -p 3000 -b 0.0.0.0
    expose:
      - "3000"
    volumes:
      - "./:/app"

  service-broker-bad-url:
    image: conjur-service-broker
    build: ./
    environment:
      << : *conjur-credentials
      CONJUR_APPLIANCE_URL: http://badurl.invalid
      CONJUR_AUTHN_API_KEY: doesntmatter
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
    command: rails s -p 3001 -b 0.0.0.0 -P tmp/pids/server1.pid
    expose:
      - "3001"
    volumes:
      - "./:/app"

  service-broker-bad-key:
    image: conjur-service-broker
    build: ./
    environment:
      << : *conjur-credentials
      SECURITY_USER_NAME: TEST_USER_NAME
      SECURITY_USER_PASSWORD: TEST_USER_PASSWORD
      CONJUR_AUTHN_API_KEY: 123badconjurkey
    command: rails s -p 3002 -b 0.0.0.0 -P tmp/pids/server2.pid
    expose:
      - "3002"
    volumes:
      - "./:/app"

  tests:
    image: conjur-service-broker
    build: ./
    environment:
      << : *conjur-credentials
    volumes:
      - "./:/app"
