#!/bin/bash

set -eo pipefail

# Run local integration tests (i.e. tests that don't require
# integration with PCF/Tanzu).

export START_SB_DEV_ENV=false
export SKIP_CONJUR_V4_TESTS=false
cd "$(dirname "$0")"
./run_tests
