# Top-level policy file

- !policy
  id: app
  body:
    - !variable
      id: secrets/org
      annotations:
        description: Org-wide secret

    - !variable
      id: secrets/space
      annotations:
        description: Space-wide secret

    - !variable
      id: secrets/app
      annotations:
        description: App-specific secret
