catalog:
  services:
    - name: conjur
      id: C024E536-6DC4-45C6-8A53-127E7F8275AB
      description: Provide applications with a Conjur role and API key
      bindable: true
      plans:
        - name: default
          id: E52A94A4-1516-4412-B239-2816EBCCB6A6
          description: Default service plan for Conjur